AllCops:
  Exclude:
    - db/*
    - config/deploy/*
    - node_modules/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 35

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

OutputSafety:
  Enabled: false
