require:
  - rubocop-rails

AllCops:
  # Auto-enable all new pending cops between releases
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - db/**/*
    - config/deploy/*
    - node_modules/**/*
    - app/views/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 35

Rails/RakeEnvironment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

OutputSafety:
  Enabled: false
