name: App Checks

on:
  # Trigger on any push to the main branch (ie, PR merge)
  push:
    branches:
      - main
  # Trigger on any push to a PR based off of main
  pull_request:
    branches:
      - main

env:
  PGUSER: postgres
  PGPASSWORD: postgres
  PGHOST: localhost
  PGPORT: 5432

jobs:
  checks:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1 # Should read from .ruby-version file
        with:
          bundler-cache: true # Runs bundle and caches gems

      - name: Set up test database
        env:
          RAILS_ENV: test
        run: bin/rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rails test
